# App + Eureka
spring.application.name=user-service
server.port=8081
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# H2 Database
spring.h2.console.enabled=true
spring.h2.console.path=/h2
spring.datasource.url=jdbc:h2:file:./Database/Data/user;AUTO_SERVER=TRUE
spring.datasource.username=se
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Keycloak security for resource server (to secure endpoints)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/maghrebia-realm

# For signup/login (Keycloak admin usage)
keycloak.auth-server-url=http://localhost:9090
keycloak.realm=maghrebia-realm
keycloak.resource=usermicroservice
keycloak.client-secret=dfaW02A3SfmiSxxa3F4SlBx1O9e3MH3T
